name: hello-world
on:
  release:
    types: [created]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "display github context"
        run: echo '${{ toJSON(github.event) }}' | jq
