name: Maven build
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8.0.302+8'
          distribution: 'adopt'

      - name: Build Maven Project
        run: mvn -B package --file pom.xml

      - name: '📦 Upload Package'
        run: gh release upload ${{github.event.release.tag_name}} target/*.jar
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
